### PR TITLE
use `Mutex` instead of `RwLock` for securing the inner data

### PR DESCRIPTION
**Pull request by hozan23**
This addresses the issue #42

### CODE REVIEW

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks! LGTM but could you please add a brief rationale in the PR **and** commit description (`git commit --amend && git push -f YOUR_REPO ues_mutex_instead_of_rwlock` in case you didn't know how to edit commits) ? While you do that, please also append `Fixes #42.` to the commit message too?

**Comment by hozan23** [comment]
@zeenix thanks, I updated the commit message.

**Review by zeenix — APPROVED** [review]
Awesome. I'm merge now but please don't forget to also update the PR description.

**Comment by fogti** [comment]
do we have some benchmarks to check that this doesn't cause sigificant performance regressions?

**Comment by zeenix** [comment]
> do we have some benchmarks to check that this doesn't cause sigificant performance regressions?

No but is there a reason we'd suspect so? 🤔

**Comment by hozan23** [comment]
@fogti In theory, it should not cause any performance regressions. #42 didn't mention any performance issues with using rwlock, but as far as I know, the only issue with rwlock is writer starvation, whereas a mutex cannot have this issue. However, I agree that we do need some benchmarks to check the performance. I will do it when I have time.

**Comment by fogti** [comment]
@hozan23 tbh, the link to the introduction of rwlock suffices for me.

**Pull request merged**
